/* Catálogo de astros nomeados que orbitam cada buraco negro.
   As etiquetas só surgem quando a câmera se aproxima e foca naquele astro em específico. */

export type CompanionKind = "star" | "cloud" | "knot" | "cluster" | "galaxy" | "planet" | "ship" | "solarsystem";

export interface Companion {
  id: string;
  kind: CompanionKind;
  name: string;
  sub: string;
  /** Velocidade estimada ou dado orbital */
  speed?: string;
  /** Distância aproximada ao centro */
  dist?: string;
  /** Dilatação temporal relativística */
  dilation?: string;
  /** semieixo maior como fração do lado menor da tela (plano orbital) */
  rFrac?: number;
  /** distância ao longo do eixo do jato, fração da tela (objetos "knot") */
  distFrac?: number;
  side?: 1 | -1;
  /** excentricidade visual da órbita */
  ecc?: number;
  /** ângulo inicial */
  th0: number;
  /** multiplicador da taxa kepleriana local */
  omScale?: number;
  /** raio base em px */
  size: number;
  /** cor do núcleo */
  col: string;
  /** cor do destaque (terminador iluminado dos planetas) */
  col2?: string;
  /** cor do brilho como "r,g,b" */
  glow: string;
  /** zoom mínimo para a etiqueta começar a ser candidata a exibição */
  labelZoom: number;
  /** desenha o fluxo de vento estelar em direção ao buraco negro */
  wind?: boolean;
}

export const COMPANIONS: Record<string, Companion[]> = {
  sgra: [
    {
      id: "s2",
      kind: "star",
      name: "Estrela S2 (S0-2)",
      sub: "Período: 16 anos · Classe B0-2 V",
      speed: "7.700 km/s (2,6% c)",
      dist: "120 UA (17 h-luz)",
      dilation: "1,0003×",
      rFrac: 0.16,
      ecc: 0.72,
      th0: 0.8,
      omScale: 1.4,
      size: 3.2,
      col: "#93c5fd",
      glow: "147,197,253",
      labelZoom: 1.8,
    },
    {
      id: "s4714",
      kind: "star",
      name: "Estrela S4714",
      sub: "Hiperveloz · rasga o espaço-tempo",
      speed: "24.000 km/s (8,0% c)",
      dist: "12,6 UA do horizonte",
      dilation: "1,0032×",
      rFrac: 0.095,
      ecc: 0.88,
      th0: 2.1,
      omScale: 2.6,
      size: 2.8,
      col: "#bfdbfe",
      glow: "191,219,254",
      labelZoom: 2.4,
    },
    {
      id: "s62",
      kind: "star",
      name: "Estrela S62",
      sub: "Período de 9,9 anos · órbita extrema",
      speed: "21.000 km/s (7,0% c)",
      dist: "16 UA no periastro",
      dilation: "1,0025×",
      rFrac: 0.115,
      ecc: 0.65,
      th0: 3.4,
      omScale: 2.1,
      size: 2.6,
      col: "#fde047",
      glow: "253,224,71",
      labelZoom: 2.2,
    },
    {
      id: "s0102",
      kind: "star",
      name: "Estrela S0-102",
      sub: "Período de 11,5 anos",
      speed: "6.200 km/s",
      dist: "260 UA",
      dilation: "1,0002×",
      rFrac: 0.22,
      ecc: 0.35,
      th0: 4.8,
      omScale: 1.1,
      size: 2.4,
      col: "#f5f3ff",
      glow: "221,214,254",
      labelZoom: 1.5,
    },
    {
      id: "g2",
      kind: "cloud",
      name: "Nuvem de Gás G2",
      sub: "Gás e poeira em estiramento de maré",
      speed: "3.000 km/s",
      dist: "260 UA no periastro",
      dilation: "1,0001×",
      rFrac: 0.29,
      ecc: 0.45,
      th0: 5.6,
      omScale: 0.8,
      size: 4.2,
      col: "#fb923c",
      glow: "251,146,60",
      labelZoom: 1.4,
    },
    {
      id: "psr-j1745",
      kind: "knot",
      name: "Magnetar PSR J1745-2900",
      sub: "Pulsar de nêutrons hipermagnetizado",
      speed: "850 km/s",
      dist: "0,33 anos-luz",
      dilation: "1,00001×",
      distFrac: 0.38,
      side: -1,
      th0: 1.5,
      size: 3.0,
      col: "#c084fc",
      glow: "192,132,252",
      labelZoom: 1.3,
    },
    {
      id: "solar-system",
      kind: "solarsystem",
      name: "Sistema Solar (Sol / Terra)",
      sub: "Braço de Órion · Você está aqui 📍",
      speed: "230 km/s (0,077% c)",
      dist: "26.670 anos-luz (8,18 kpc)",
      dilation: "1,00000000002×",
      rFrac: 0.44,
      ecc: 0.06,
      th0: 1.15,
      omScale: 0.18,
      size: 4.0,
      col: "#fbbf24",
      col2: "#38bdf8",
      glow: "251,191,36",
      labelZoom: 1.0,
    },
  ],

  m87: [
    {
      id: "hst1",
      kind: "knot",
      name: "Nó de Choque HST-1",
      sub: "Emissão superluminal aparente no jato",
      speed: "6c (aparente)",
      dist: "280 anos-luz",
      dilation: "4,5× (Lorentz)",
      distFrac: 0.22,
      side: 1,
      th0: 2.2,
      size: 3.2,
      col: "#93c5fd",
      glow: "147,197,253",
      labelZoom: 1.5,
    },
    {
      id: "jet-outer",
      kind: "knot",
      name: "Lobo Terminal do Jato",
      sub: "Frente de choque sincrotron",
      speed: "0,99c relativístico",
      dist: "5.000 anos-luz",
      dilation: "7,1×",
      distFrac: 0.46,
      side: 1,
      th0: 0.5,
      size: 4.0,
      col: "#60a5fa",
      glow: "96,165,250",
      labelZoom: 1.1,
    },
    {
      id: "gc",
      kind: "cluster",
      name: "Aglomerado Globular",
      sub: "M87 abriga ~12.000 enxames estelares",
      speed: "450 km/s",
      dist: "1.200 anos-luz",
      dilation: "1,00001×",
      rFrac: 0.28,
      ecc: 0.1,
      th0: 5.0,
      omScale: 0.45,
      size: 3.6,
      col: "#fde047",
      glow: "253,224,71",
      labelZoom: 1.3,
    },
    {
      id: "ngc4486b",
      kind: "galaxy",
      name: "Galáxia NGC 4486B",
      sub: "Anã elíptica sendo canibalizada",
      speed: "380 km/s",
      dist: "4.500 anos-luz",
      dilation: "1,000005×",
      rFrac: 0.44,
      ecc: 0.08,
      th0: 1.9,
      omScale: 0.35,
      size: 4.5,
      col: "#fed7aa",
      glow: "254,215,170",
      labelZoom: 1.1,
    },
    {
      id: "tde-star",
      kind: "star",
      name: "Estrela TDE em Ruptura",
      sub: "Espaguetificação por forças de maré",
      speed: "32.000 km/s (10,7% c)",
      dist: "380 UA do horizonte",
      dilation: "1,006×",
      rFrac: 0.12,
      ecc: 0.85,
      th0: 3.7,
      omScale: 1.8,
      size: 3.2,
      col: "#f43f5e",
      glow: "244,63,94",
      labelZoom: 2.2,
    },
  ],

  gargantua: [
    {
      id: "g-miller",
      kind: "planet",
      name: "Planeta Miller",
      sub: "Mundo oceânico · ondas gigantescas",
      speed: "0,55c (55% da luz)",
      dist: "Borda da Ergosfera",
      dilation: "61.320× (1h = 7 anos na Terra)",
      rFrac: 0.078,
      ecc: 0.04,
      th0: 1.8,
      omScale: 1.1,
      size: 4.0,
      col: "#38bdf8",
      col2: "#bae6fd",
      glow: "56,189,248",
      labelZoom: 2.2,
    },
    {
      id: "g-lander",
      kind: "ship",
      name: "Módulo Lander",
      sub: "Veículo de descida a Miller",
      speed: "0,55c em aproximação",
      dist: "Sub-órbita de Miller",
      dilation: "60.000×",
      rFrac: 0.098,
      ecc: 0.05,
      th0: 2.3,
      omScale: 1.02,
      size: 2.2,
      col: "#ffffff",
      glow: "186,230,253",
      labelZoom: 3.0,
    },
    {
      id: "g-ranger",
      kind: "ship",
      name: "Nave Ranger",
      sub: "Reconhecimento da tripulação",
      speed: "0,52c",
      dist: "Vetor de escape intermediário",
      dilation: "45.000×",
      rFrac: 0.122,
      ecc: 0.08,
      th0: 2.8,
      omScale: 0.95,
      size: 2.4,
      col: "#ffffff",
      glow: "186,230,253",
      labelZoom: 2.8,
    },
    {
      id: "g-endurance",
      kind: "ship",
      name: "Estação Endurance",
      sub: "Nave orbital anelar de 12 módulos",
      speed: "0,35c",
      dist: "Órbita de segurança estável",
      dilation: "1,07×",
      rFrac: 0.165,
      ecc: 0.06,
      th0: 5.2,
      omScale: 0.82,
      size: 3.2,
      col: "#f8fafc",
      glow: "248,250,252",
      labelZoom: 1.9,
    },
    {
      id: "g-mann",
      kind: "planet",
      name: "Planeta Mann",
      sub: "Mundo inóspito com nuvens de amônia",
      speed: "14.000 km/s",
      dist: "8,5 UA em média",
      dilation: "1,001×",
      rFrac: 0.25,
      ecc: 0.22,
      th0: 3.9,
      omScale: 0.58,
      size: 3.8,
      col: "#cbd5e1",
      col2: "#f1f5f9",
      glow: "203,213,225",
      labelZoom: 1.5,
    },
    {
      id: "g-edmunds",
      kind: "planet",
      name: "Planeta Edmunds",
      sub: "Mundo rochoso habitável (Lázaro)",
      speed: "6.200 km/s",
      dist: "18,2 UA (zona segura)",
      dilation: "1,00003× (tempo normal)",
      rFrac: 0.37,
      ecc: 0.12,
      th0: 0.8,
      omScale: 0.44,
      size: 3.6,
      col: "#34d399",
      col2: "#a7f3d0",
      glow: "52,211,153",
      labelZoom: 1.2,
    },
  ],

  cygx1: [
    {
      id: "hde226868",
      kind: "star",
      name: "HDE 226868",
      sub: "Supergigante Azul O9.7Iab · 40 M☉",
      speed: "410 km/s orbital",
      dist: "0,2 UA (30 milhões km)",
      dilation: "1,000005×",
      rFrac: 0.34,
      ecc: 0.02,
      th0: 0.6,
      omScale: 0.65,
      size: 7.2,
      col: "#93c5fd",
      col2: "#dbeafe",
      glow: "147,197,253",
      labelZoom: 1.3,
      wind: true,
    },
    {
      id: "l1-bridge",
      kind: "cloud",
      name: "Ponto L1 & Ponte de Plasma",
      sub: "Transferência de massa Roche",
      speed: "2.500 km/s",
      dist: "0,08 UA",
      dilation: "1,0001×",
      rFrac: 0.20,
      ecc: 0.06,
      th0: 0.6,
      omScale: 0.65,
      size: 4.2,
      col: "#c084fc",
      glow: "192,132,252",
      labelZoom: 2.1,
    },
    {
      id: "hotspot",
      kind: "knot",
      name: "Hot Spot de Colisão",
      sub: "Choque do gás no disco rápido",
      speed: "45.000 km/s (15% c)",
      dist: "0,03 UA",
      dilation: "1,011×",
      rFrac: 0.11,
      ecc: 0.12,
      th0: 1.2,
      omScale: 1.9,
      size: 3.4,
      col: "#f43f5e",
      glow: "244,63,94",
      labelZoom: 3.0,
    },
    {
      id: "jet-x",
      kind: "knot",
      name: "Jato Bipolar de Raios-X",
      sub: "Ejeções periódicas de elétrons",
      speed: "0,92c (92% de c)",
      dist: "Propaga-se no meio estelar",
      dilation: "2,55×",
      distFrac: 0.32,
      side: 1,
      th0: 1.1,
      size: 3.6,
      col: "#38bdf8",
      glow: "56,189,248",
      labelZoom: 1.4,
    },
  ],

  ton618: [
    {
      id: "torus",
      kind: "cloud",
      name: "Torus de Poeira Molecular",
      sub: "Anel circumnuclear colossal",
      speed: "1.200 km/s",
      dist: "100 anos-luz de espessura",
      dilation: "1,00002×",
      rFrac: 0.40,
      ecc: 0.1,
      th0: 2.5,
      omScale: 0.4,
      size: 6.5,
      col: "#f59e0b",
      glow: "245,158,11",
      labelZoom: 1.1,
    },
    {
      id: "blr-alpha",
      kind: "cloud",
      name: "Nuvem Relativística BLR-Alpha",
      sub: "Região de linhas largas ultra-veloz",
      speed: "7.000 km/s (2,3% c)",
      dist: "0,5 anos-luz",
      dilation: "1,0003×",
      rFrac: 0.20,
      ecc: 0.25,
      th0: 1.2,
      omScale: 1.1,
      size: 4.8,
      col: "#ec4899",
      glow: "236,72,153",
      labelZoom: 1.8,
    },
    {
      id: "hv-exodus",
      kind: "star",
      name: "Estrela Hiperveloz HV-Exodus",
      sub: "Ejetada por estilingue gravitacional",
      speed: "18.000 km/s (6% c)",
      dist: "Trajetória hiperbólica de escape",
      dilation: "1,0018×",
      rFrac: 0.28,
      ecc: 0.88,
      th0: 4.1,
      omScale: 1.4,
      size: 3.2,
      col: "#a855f7",
      glow: "168,85,247",
      labelZoom: 1.6,
    },
    {
      id: "pop3-cluster",
      kind: "cluster",
      name: "Aglomerado Primordial Pop III",
      sub: "Enxame estelar do universo jovem",
      speed: "600 km/s",
      dist: "400 anos-luz do núcleo",
      dilation: "1,00001×",
      rFrac: 0.46,
      ecc: 0.15,
      th0: 0.4,
      omScale: 0.32,
      size: 5.0,
      col: "#38bdf8",
      glow: "56,189,248",
      labelZoom: 1.0,
    },
  ],

  // Fallback de compatibilidade
  quasar: [],
};

// Aliás para o quasar antigo apontar para ton618
COMPANIONS.quasar = COMPANIONS.ton618;
